// <auto-generated />
using Microservices.Services.DependenciasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservices.Services.DependenciasAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservices.Services.DependenciasAPI.Models.Dependencia", b =>
                {
                    b.Property<int>("DependenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependenciaId"));

                    b.Property<string>("DependenciaAbrev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DependenciaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DependenciaId");

                    b.ToTable("Dependencias");

                    b.HasData(
                        new
                        {
                            DependenciaId = 1,
                            DependenciaAbrev = "DIRECOMAR",
                            DependenciaName = "Direccion General de Economia",
                            IsActive = true
                        },
                        new
                        {
                            DependenciaId = 2,
                            DependenciaAbrev = "DIPERADMON",
                            DependenciaName = "Direccion de Administracion de Personal",
                            IsActive = true
                        },
                        new
                        {
                            DependenciaId = 3,
                            DependenciaAbrev = "DIRESNA",
                            DependenciaName = "Escuela Naval del Peru",
                            IsActive = true
                        },
                        new
                        {
                            DependenciaId = 4,
                            DependenciaAbrev = "COMFUIMAR",
                            DependenciaName = "Fuerza de Infanteria de la Marina",
                            IsActive = true
                        },
                        new
                        {
                            DependenciaId = 5,
                            DependenciaAbrev = "COMFOES",
                            DependenciaName = "Fuerza de Operacines Especiales",
                            IsActive = true
                        },
                        new
                        {
                            DependenciaId = 6,
                            DependenciaAbrev = "DIFOSECE",
                            DependenciaName = "Fondo de Seguro y Cesacion",
                            IsActive = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
