// <auto-generated />
using Microservices.Services.GradosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservices.Services.GradosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservices.Services.GradosAPI.Models.Grado", b =>
                {
                    b.Property<int>("GradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradoId"));

                    b.Property<string>("GradoAbrev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GradoId");

                    b.ToTable("Grados");

                    b.HasData(
                        new
                        {
                            GradoId = 1,
                            GradoAbrev = "Valm.",
                            GradoCode = "100",
                            GradoName = "Vicealmirante",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 2,
                            GradoAbrev = "Contralm.",
                            GradoCode = "200",
                            GradoName = "Contralmirante",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 3,
                            GradoAbrev = "C.de N.",
                            GradoCode = "300",
                            GradoName = "Capitan de Navio",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 4,
                            GradoAbrev = "C.de F.",
                            GradoCode = "400",
                            GradoName = "Capitan de Fragata",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 5,
                            GradoAbrev = "C.de C.",
                            GradoCode = "500",
                            GradoName = "Capitan de Corbeta",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 6,
                            GradoAbrev = "Tte. 1",
                            GradoCode = "600",
                            GradoName = "Teniente Primero",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 7,
                            GradoAbrev = "Tte. 2",
                            GradoCode = "600",
                            GradoName = "Teniente Segundo",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 8,
                            GradoAbrev = "Afgta.",
                            GradoCode = "800",
                            GradoName = "Alferez de Frataga  ",
                            IsActive = true
                        },
                        new
                        {
                            GradoId = 9,
                            GradoAbrev = "SPA",
                            GradoCode = "1000",
                            GradoName = "Servidor Publico A",
                            IsActive = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
